/*
    ALTER TABLE SCRIPTS FOR COMPANY DATABASE ALONG WITH FOREIGN KEYS.
    CREATED BY:- 
    NAME :          SUBHAM BASU ROY CHOWDHURY
    ROLL :          MT2022118
   
*/

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_SUPER_SSN FOREIGN KEY (SUPER_SSN) REFERENCES EMPLOYEE(SSN);

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_DNO FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE DEPARTMENT 
ADD CONSTRAINT FK_MGR_SSN FOREIGN KEY (MGR_SSN) REFERENCES EMPLOYEE(SSN);

ALTER TABLE DEPT_LOCATIONS 
ADD CONSTRAINT FK_DNUMBER FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE PROJECT
ADD CONSTRAINT FK_DNUM FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_PNO FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER);

ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_ESSN FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN);


ALTER TABLE `DEPENDENT`
ADD CONSTRAINT FK_DPND_ESSN FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN);

